### ISSUE TITLE
Photos from DSLR cameras with identical names but different dates

### ISSUE THREAD

**Issue by goeland86** [maciekberry/MonumentPhotoExporter#1]
Hi,

Just wanted to post of a problem I ran into when trying to export my Monument photo library with your tool.

I have a DSLR and tend to take a **lot** of photos when I go on various trips. DSLRs number photos consecutively... with 4 digits. Unsurprisingly, I'm running into the issue of having duplicate photo IDs a couple of years apart.

In my case:
```
$ find mnt/ -name IMG_1583.CR3 -type f
monument/User1/Canon Canon EOS 90D/2020/09/IMG_1583.CR3
monument/User1/Canon Canon EOS 90D/2022/06/IMG_1583.CR3
```

I then obviously get this error:
```
WARNING: output/Jon_28831/PHOTOS_WITHOUT_ALBUM/IMG_1583.CR3 -> the file existed already, changing to IMG_1583-31eed9ade07134f0fe806f78a6c5f2de35f9d5b6.CR3
java.nio.file.FileAlreadyExistsException: output/Jon_28831/PHOTOS_WITHOUT_ALBUM/IMG_1583-31eed9ade07134f0fe806f78a6c5f2de35f9d5b6.CR3
	at java.base/sun.nio.fs.UnixFileSystem.copy(UnixFileSystem.java:1030)
	at java.base/sun.nio.fs.UnixFileSystemProvider.copy(UnixFileSystemProvider.java:300)
	at java.base/java.nio.file.Files.copy(Files.java:1304)
	at Exporter.copyContent(Exporter.java:79)
	at Exporter.export(Exporter.java:209)
	at Main.main(Main.java:55)
```

I think it should be easy enough to modify (and will submit a PR to that effect) such that photos with no albums get put in a hierarchy following the template: `yyyy/mm/dd`  - which is what [Shotwell](https://wiki.gnome.org/Apps/Shotwell) uses by default when importing a photo library. Given that few people are likely to take 10k or more photos in a single day, this seems like the most reasonable way to organize photos without albums imo.

If a different or more sensible proposal for dealing with this scenario exists, I'm all ears.

**Comment by maciekberry** [comment]
Understood. Let me think this through until the weekend :)
